// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/edapi/bankbills/analyse/jyds/counterparty/class": {
            "get": {
                "description": "交易对手-对手方分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.JydsClassResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/jyds/counterparty/overview": {
            "get": {
                "description": "交易对手-对手方概览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.JydsOverviewResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/jyds/monitor_object": {
            "get": {
                "description": "交易对手-重点监测对象",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.JydsMonitorObjectResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/jyhz/abnormal/transaction": {
            "get": {
                "description": "交易汇总-异常交易",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.AbnormalTransactionResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/jyhz/balance/fluctuation": {
            "get": {
                "description": "交易汇总-余额波动",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.BalanceFluctuationResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/jyhz/transaction/distribution": {
            "get": {
                "description": "交易汇总-交易分布",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.TransactionDistribution"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/lsyz/authenticity": {
            "get": {
                "description": "流水验证-数据真实性",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.LsyzAResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/lsyz/completeness/account": {
            "get": {
                "description": "流水验证-数据完整性-账号信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.LsyzCAccountResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/lsyz/completeness/balance": {
            "get": {
                "description": "流水验证-数据完整性-余额完整",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.LsyzBalanceResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/analyse/lsyz/completeness/summary": {
            "get": {
                "description": "流水验证-数据完整性-摘要完整",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前项目下筛选的文档 多个以英文逗号','拼接 不超过30个",
                        "name": "doc_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 2022-07-24",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间 2022-07-23",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.LsyzSummaryResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/project/add": {
            "get": {
                "description": "项目管理-新建项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目备注",
                        "name": "note",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "description": "项目类型 1:企业 2:个人 3:其他",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.AddProjectResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/project/query": {
            "get": {
                "description": "项目管理-项目列表",
                "parameters": [
                    {
                        "enum": [
                            0,
                            1
                        ],
                        "type": "integer",
                        "description": "项目创建时间排序搜索项 0:默认倒序 1:正序",
                        "name": "date_desc",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "结束时间 秒级时间戳",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字搜索 包含项目名称和备注的模糊匹配",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "minimum": 5,
                        "type": "integer",
                        "description": "默认5条/页",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "第一页开始",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "开始时间 秒级时间戳",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "description": "项目类型搜索项 1:企业 2:个人 3:其他",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.Result1"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/rest.ProjectListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/edapi/bankbills/project/update": {
            "get": {
                "description": "项目管理-更新项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目备注",
                        "name": "note",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "description": "项目类型 1:企业 2:个人 3:其他",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Result1"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.AbnormalTradeI": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "ending_balance": {
                    "description": "期末余额",
                    "type": "integer"
                },
                "initial_balance": {
                    "description": "初期余额",
                    "type": "integer"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "summary": {
                    "description": "交易摘要",
                    "type": "string"
                },
                "trade_amount": {
                    "description": "交易金额",
                    "type": "integer"
                },
                "trade_time": {
                    "description": "交易时间",
                    "type": "string"
                }
            }
        },
        "rest.AbnormalTradeI1": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "ending_balance": {
                    "description": "期末余额",
                    "type": "integer"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "summary": {
                    "description": "交易摘要",
                    "type": "string"
                },
                "trade_amount": {
                    "description": "交易金额",
                    "type": "integer"
                },
                "trade_time": {
                    "description": "交易时间",
                    "type": "string"
                }
            }
        },
        "rest.AbnormalTransactionResp": {
            "type": "object",
            "properties": {
                "high_frequency_trading": {
                    "description": "高频交易",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.HighFrequencyTradingI"
                        }
                    ]
                },
                "large_num": {
                    "description": "大额交易流水总数",
                    "type": "integer"
                },
                "large_transaction": {
                    "description": "大额交易",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.LargeTransactionI"
                    }
                },
                "suspicious_num": {
                    "description": "可以交易流水总数",
                    "type": "integer"
                },
                "suspicious_transaction": {
                    "description": "可疑交易",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.SuspiciousTransactionI"
                    }
                }
            }
        },
        "rest.AddProjectResp": {
            "type": "object",
            "properties": {
                "project_id": {
                    "description": "新建成功之后的项目id",
                    "type": "integer"
                }
            }
        },
        "rest.AssociateInfoI": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "银行账户",
                    "type": "string"
                },
                "name": {
                    "description": "隶属银行",
                    "type": "string"
                }
            }
        },
        "rest.BalanceFluctuationResp": {
            "type": "object",
            "properties": {
                "balance_fluctuation": {
                    "description": "余额波动",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.BalanceInfo"
                    }
                }
            }
        },
        "rest.BalanceInfo": {
            "type": "object",
            "properties": {
                "avg_balance": {
                    "description": "月均余额",
                    "type": "integer"
                },
                "timer": {
                    "description": "月 2022-01",
                    "type": "string"
                },
                "volatility": {
                    "description": "波动率 20%",
                    "type": "string"
                }
            }
        },
        "rest.BalanceTypeI": {
            "type": "object",
            "properties": {
                "timer": {
                    "description": "2023-01",
                    "type": "string"
                },
                "type": {
                    "description": "1 缺失 2 错误 3 正确",
                    "type": "integer"
                }
            }
        },
        "rest.ClassTradeInfo": {
            "type": "object",
            "properties": {
                "in_amount": {
                    "description": "收入金额",
                    "type": "integer"
                },
                "name": {
                    "description": "对手方名称",
                    "type": "string"
                },
                "out_amount": {
                    "description": "支出金额",
                    "type": "integer"
                }
            }
        },
        "rest.ClassTradeInfo1": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "交易金额",
                    "type": "integer"
                },
                "name": {
                    "description": "对手方名称",
                    "type": "string"
                }
            }
        },
        "rest.HighFrequencyTradingI": {
            "type": "object",
            "properties": {
                "income": {
                    "description": "收入",
                    "type": "integer"
                },
                "income_num": {
                    "description": "收入笔数",
                    "type": "integer"
                },
                "name": {
                    "description": "对手方",
                    "type": "string"
                },
                "pay": {
                    "description": "支出",
                    "type": "integer"
                },
                "pay_num": {
                    "description": "支出笔数",
                    "type": "integer"
                }
            }
        },
        "rest.InterestReportI": {
            "type": "object",
            "properties": {
                "estimate_interest": {
                    "description": "预估利息 单位元",
                    "type": "integer"
                },
                "interest": {
                    "description": "利息 单位元",
                    "type": "integer"
                },
                "interest_time": {
                    "description": "结息日期 后端格式化之后返回",
                    "type": "string"
                },
                "summary": {
                    "description": "交易摘要",
                    "type": "string"
                },
                "trade_time": {
                    "description": "交易日期 后端格式化之后返回",
                    "type": "string"
                }
            }
        },
        "rest.JydsClassResp": {
            "type": "object",
            "properties": {
                "income": {
                    "description": "收入",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsClassSummaryI"
                        }
                    ]
                },
                "pay": {
                    "description": "支持",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsClassSummaryP"
                        }
                    ]
                },
                "summary": {
                    "description": "汇总",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsClassSummary"
                        }
                    ]
                }
            }
        },
        "rest.JydsClassSummary": {
            "type": "object",
            "properties": {
                "institutional_clients": {
                    "description": "机构客户数量",
                    "type": "integer"
                },
                "natural_person": {
                    "description": "自然人数量",
                    "type": "integer"
                },
                "other": {
                    "description": "其他数量",
                    "type": "integer"
                },
                "own": {
                    "description": "自己数量",
                    "type": "integer"
                },
                "trade_info": {
                    "description": "对手方交易明细 top8",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ClassTradeInfo"
                    }
                }
            }
        },
        "rest.JydsClassSummaryI": {
            "type": "object",
            "properties": {
                "institutional_clients": {
                    "description": "机构客户数量",
                    "type": "integer"
                },
                "natural_person": {
                    "description": "自然人数量",
                    "type": "integer"
                },
                "other": {
                    "description": "其他数量",
                    "type": "integer"
                },
                "own": {
                    "description": "自己数量",
                    "type": "integer"
                },
                "trade_info": {
                    "description": "对手方收入明细 top8",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ClassTradeInfo1"
                    }
                }
            }
        },
        "rest.JydsClassSummaryP": {
            "type": "object",
            "properties": {
                "institutional_clients": {
                    "description": "机构客户数量",
                    "type": "integer"
                },
                "natural_person": {
                    "description": "自然人数量",
                    "type": "integer"
                },
                "other": {
                    "description": "其他数量",
                    "type": "integer"
                },
                "own": {
                    "description": "自己数量",
                    "type": "integer"
                },
                "trade_info": {
                    "description": "对手方支出明细 top8",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ClassTradeInfo1"
                    }
                }
            }
        },
        "rest.JydsMonitorObjectResp": {
            "type": "object",
            "properties": {
                "income": {
                    "description": "收入",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsMonitorObjectSummary"
                        }
                    ]
                },
                "pay": {
                    "description": "支出",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsMonitorObjectSummary"
                        }
                    ]
                },
                "summary": {
                    "description": "汇总",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rest.JydsMonitorObjectSummary"
                        }
                    ]
                }
            }
        },
        "rest.JydsMonitorObjectSummary": {
            "type": "object",
            "properties": {
                "asset_management": {
                    "description": "资产管理",
                    "type": "integer"
                },
                "cultural_artistic_items": {
                    "description": "文化艺术品",
                    "type": "integer"
                },
                "finance": {
                    "description": "金融",
                    "type": "integer"
                },
                "financial_assets_equities": {
                    "description": "金融资产权益",
                    "type": "integer"
                },
                "financial_services": {
                    "description": "金融服务",
                    "type": "integer"
                },
                "financing": {
                    "description": "融资",
                    "type": "integer"
                },
                "guarantee": {
                    "description": "担保",
                    "type": "integer"
                },
                "investment": {
                    "description": "投资",
                    "type": "integer"
                },
                "lease": {
                    "description": "租赁",
                    "type": "integer"
                },
                "pawn": {
                    "description": "地产",
                    "type": "integer"
                },
                "precious_metals_investment": {
                    "description": "贵金属投资",
                    "type": "integer"
                },
                "property_purchase": {
                    "description": "置业",
                    "type": "integer"
                },
                "real_estate": {
                    "description": "房地产",
                    "type": "integer"
                },
                "small_loan": {
                    "description": "小贷",
                    "type": "integer"
                },
                "total_num": {
                    "description": "所有流水的条数",
                    "type": "integer"
                },
                "trade_info": {
                    "description": "所有流水详情",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.MonitorTradeInfo"
                    }
                },
                "wealth_management": {
                    "description": "财富管理",
                    "type": "integer"
                }
            }
        },
        "rest.JydsOverviewResp": {
            "type": "object",
            "properties": {
                "income": {
                    "description": "收入",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.JydsOverviewTradeInfo"
                    }
                },
                "income_number": {
                    "description": "收入流水笔数 这里默认15条 如果少于15 例如只有9条那组件中第三页就不需要了",
                    "type": "integer"
                },
                "pay": {
                    "description": "支出",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.JydsOverviewTradeInfo"
                    }
                },
                "pay_number": {
                    "description": "支出流水笔数 这里默认15条 如果少于15 例如只有9条那组件中第三页就不需要了",
                    "type": "integer"
                },
                "summary": {
                    "description": "汇总",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.JydsOverviewTradeInfo"
                    }
                },
                "summary_number": {
                    "description": "流水汇总笔数 这里默认15条 如果少于15 例如只有9条那组件中第三页就不需要了",
                    "type": "integer"
                }
            }
        },
        "rest.JydsOverviewTradeInfo": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "amount": {
                    "description": "交易金额",
                    "type": "integer"
                },
                "id": {
                    "description": "序号",
                    "type": "integer"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "trade_number": {
                    "description": "交易笔数",
                    "type": "integer"
                },
                "trade_time": {
                    "description": "交易时间段",
                    "type": "string"
                }
            }
        },
        "rest.LargeTransactionI": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "amount": {
                    "description": "金额",
                    "type": "integer"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "proportion": {
                    "description": "当月占比",
                    "type": "string"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                }
            }
        },
        "rest.LsyzAResp": {
            "type": "object",
            "properties": {
                "abnormal_times": {
                    "description": "结息金额异常次数",
                    "type": "integer"
                },
                "actual_interest": {
                    "description": "实结息",
                    "type": "integer"
                },
                "interest_report": {
                    "description": "结息报表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.InterestReportI"
                    }
                },
                "should_interest": {
                    "description": "应结息",
                    "type": "integer"
                },
                "total_interest": {
                    "description": "总结息金额",
                    "type": "integer"
                }
            }
        },
        "rest.LsyzBalanceResp": {
            "type": "object",
            "properties": {
                "abnormal_trade": {
                    "description": "异常记录",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.AbnormalTradeI"
                    }
                },
                "balance_type": {
                    "description": "月余额类型",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.BalanceTypeI"
                    }
                },
                "error_num": {
                    "description": "月错误总月数",
                    "type": "integer"
                },
                "interval_type": {
                    "description": "区间类型 0月 1周",
                    "type": "integer"
                },
                "total_num": {
                    "description": "余额总月数",
                    "type": "integer"
                }
            }
        },
        "rest.LsyzCAccountResp": {
            "type": "object",
            "properties": {
                "none_same_name_account": {
                    "description": "非同名账户信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.NSMInfo"
                    }
                },
                "theme_account": {
                    "description": "主体账户",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ThemeAccountInfo"
                    }
                }
            }
        },
        "rest.LsyzSummaryResp": {
            "type": "object",
            "properties": {
                "abnormal_trade": {
                    "description": "异常记录",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.AbnormalTradeI1"
                    }
                },
                "error_num": {
                    "description": "摘要缺失月数",
                    "type": "integer"
                },
                "interval_type": {
                    "description": "区间类型 0月 1周",
                    "type": "integer"
                },
                "summary_type": {
                    "description": "月摘要类型",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.SummaryTypeI"
                    }
                },
                "total_num": {
                    "description": "摘要总月数",
                    "type": "integer"
                }
            }
        },
        "rest.MonitorTradeInfo": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "signal": {
                    "description": "预警信号",
                    "type": "string"
                },
                "trade_number": {
                    "description": "交易笔数",
                    "type": "integer"
                },
                "trade_time": {
                    "description": "交易时间",
                    "type": "string"
                }
            }
        },
        "rest.NSMInfo": {
            "type": "object",
            "properties": {
                "trade_account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "trade_name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "trade_period": {
                    "description": "交易时间段",
                    "type": "string"
                },
                "transfer_in": {
                    "description": "向同名账户转入 单位元",
                    "type": "integer"
                },
                "transfer_in_times": {
                    "description": "向同名账户转入次数",
                    "type": "integer"
                },
                "transfer_out": {
                    "description": "向同名账户转出 单位元",
                    "type": "integer"
                },
                "transfer_out_times": {
                    "description": "向同名账户转出次数",
                    "type": "integer"
                }
            }
        },
        "rest.ProjectListI": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "项目创建时间",
                    "type": "integer"
                },
                "doc_count": {
                    "description": "当前项目下文件总数",
                    "type": "integer"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "note": {
                    "description": "项目备注",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目id",
                    "type": "integer"
                },
                "type": {
                    "description": "项目类型",
                    "type": "integer"
                }
            }
        },
        "rest.ProjectListResp": {
            "type": "object",
            "properties": {
                "amount_count": {
                    "description": "金额总数",
                    "type": "integer"
                },
                "count": {
                    "description": "项目总数",
                    "type": "integer"
                },
                "doc_count": {
                    "description": "文档总数",
                    "type": "integer"
                },
                "project_list": {
                    "description": "项目详情",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ProjectListI"
                    }
                },
                "report_count": {
                    "description": "报告总数",
                    "type": "integer"
                }
            }
        },
        "rest.Result1": {
            "type": "object",
            "properties": {
                "data": {},
                "err": {},
                "ret": {
                    "type": "integer"
                }
            }
        },
        "rest.SummaryTypeI": {
            "type": "object",
            "properties": {
                "timer": {
                    "description": "2023-01",
                    "type": "string"
                },
                "type": {
                    "description": "1 摘要完整 2 摘要缺失",
                    "type": "integer"
                }
            }
        },
        "rest.SuspiciousTransactionI": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "交易账号",
                    "type": "string"
                },
                "amount": {
                    "description": "金额",
                    "type": "integer"
                },
                "name": {
                    "description": "交易户名",
                    "type": "string"
                },
                "time": {
                    "description": "时间",
                    "type": "string"
                }
            }
        },
        "rest.ThemeAccountInfo": {
            "type": "object",
            "properties": {
                "associate_info": {
                    "description": "主体账户涉及的银行账户",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.AssociateInfoI"
                    }
                },
                "theme_name": {
                    "description": "主体账户名",
                    "type": "string"
                }
            }
        },
        "rest.TradeAmountI": {
            "type": "object",
            "properties": {
                "income": {
                    "description": "当月收入",
                    "type": "integer"
                },
                "pay": {
                    "description": "当月支出",
                    "type": "integer"
                },
                "timer": {
                    "description": "月 2022-01",
                    "type": "string"
                }
            }
        },
        "rest.TradeNumberI": {
            "type": "object",
            "properties": {
                "income_num": {
                    "description": "当月收入笔数",
                    "type": "integer"
                },
                "pay_num": {
                    "description": "当月支出笔数",
                    "type": "integer"
                },
                "timer": {
                    "description": "月 2022-01",
                    "type": "string"
                }
            }
        },
        "rest.TransactionDistribution": {
            "type": "object",
            "properties": {
                "trade_amount": {
                    "description": "交易金额",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.TradeAmountI"
                    }
                },
                "trade_number": {
                    "description": "交易笔数",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.TradeNumberI"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
